### ISSUE TITLE
"undefined is not a constructor" error when used in a SAFE stack app

### ISSUE THREAD

**Issue by danyx23** [Zaid-Ajaj/Elmish.SweetAlert#1]
First of all thanks a lot for Elmish.SweetAlert, it's a very useful library! We recently upgraded our safe stack app to the latest version as well as a bunch of libraries we used among them Elmish.SweetAlert and unfortunately the current version of Elmish.SweetAlert and the SAFE stack template seem not to work together. I reproduced the error in an empty SAFE stack application starting from the default template and just adding SweetAlert as per the instructions and adding a sweetalert when the Increment message is sent

The error that happes is javascript exception at runtime - you get an exception "undefined is not a constructor" inside sweetalert.js - apparently inside fire the Swat variable is assigned from *this* and *this* is undefined in this setup. Maybe this has something to do with the webpack setup in the SAFE stack template?

Please let me know if you would like me to upload the SAFE stack demo of the error when using SweetAlert or if I can help in other ways. I tried debugging what goes wrong here but my Javascript skills are weak and I was hoping that you would maybe have an idea what fails in this setup. Thanks!

**Comment by Zaid-Ajaj** [comment]
Hello there @danyx23, this error looks familiar, I think it has to do with the breaking changes in the required `sweetalert2` library, what version do you have installed inside your package.json or the lock the files?

If you happen to use [Femto](https://github.com/Zaid-Ajaj/Femto) (which you absolutely should), then simply run `femto --resolve` inside your front-end's project directory and let it resolve the right packages for you

**Comment by Zaid-Ajaj** [comment]
> Please let me know if you would like me to upload the SAFE stack demo of the error when using SweetAlert or if I can help in other ways. I tried debugging what goes wrong here but my Javascript skills are weak and I was hoping that you would maybe have an idea what fails in this setup. Thanks!

An example repro would be awesome, other than that, I will give it a try myself starting from the SAFE template

**Comment by danyx23** [comment]
Wow, thanks for your fast reply! I'll create a sample repo. I am at the latest sweetalert2 version (8.17.1) but also tried to fix it to the one that is given in Elmish.SweetAlert (8.5.0). I tried femto but it didn't complain about anything other than bulma being a dev-dependency.

**Comment by danyx23** [comment]
The example repo is here: https://github.com/danyx23/safe-stack-sweet-alert-debug

When you run it and press the increase button the error happens

**Comment by Zaid-Ajaj** [comment]
I will check it out today, but from a first glance it seems that the installed version of sweetalert is not the one the library requires 8.17 (needs 8.5 installed) and femto is not complaining? weird stuff, I will keep you posted

**Comment by Zaid-Ajaj** [comment]
Alright, I am able to reproduce the problem, even after updating back to v8.5

**Comment by Zaid-Ajaj** [comment]
> apparently inside fire the Swat variable is assigned from this and this is undefined in this setup

The problem was the fable import: newer fable versions seem to create a new function when importing another function (fire) using a function type which should work just fine but in this very weird case, the `this` lost it's context and meaning when used from the newly created function so I changed the import syntax such that it doesn't create a new function/new scope

Can you please update from v3.1.0 to v3.2.0 and verify that the problem indeed has been fixed? Thank you!

**Comment by danyx23** [comment]
Yes, indeed it works now - thanks a lot! Unfortunately I won't be at Fable conf this year but when we meet next time I owe you an upscale beverage of your choice :).

(P.S.: if others find this issue as well and upgrading doesn't work for them immediately - there seems to be a Paket bug at the moment that doesn't update package versions correctly in the cache inside the /obj folder. If upgrading doesn't work, try deleting the /obj folder for fable project. Paket issue: https://github.com/fsprojects/Paket/issues/3618 )

**Comment by Zaid-Ajaj** [comment]
>Yes, indeed it works now - thanks a lot! 

Awesome, thanks for confirming!

> Unfortunately I won't be at Fable conf this year but when we meet next time I owe you an upscale beverage of your choice :).

Sounds like a plan 🍻
