### ISSUE TITLE
Icons do not show

### ISSUE THREAD

**Issue by isaacabraham** [Zaid-Ajaj/Elmish.SweetAlert#2]
No icons are shown e.g.

```fsharp
let alert = SweetAlert.SimpleAlert("Test").Type(SweetAlert.AlertType.Question)
```

Shows this:

![image](https://user-images.githubusercontent.com/1781813/68679072-761f0d80-055f-11ea-845b-b73f5e1222f0.png)

Notice that no question icon is shown. How do I get it to show?

**Comment by Zaid-Ajaj** [comment]
Hello @isaacabraham, looking at the docs of SweetAlert, it seems that version 9.x introduces a breaking change with icon keys. You should install SweetAlert version 8.x (written in README) to make the icons work

**Comment by Zaid-Ajaj** [comment]
I just published a new version with proper [Femto](https://github.com/Zaid-Ajaj/Femto) metadata so you can update Elmish.SweetAlert to latest and then run `femto --resolve` inside your project directory and it will take care of the rest for you
